# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://chavacano.org/
baseurl: http://chavacano.org/
title: Coloring Colorao
author: Marcelo Yuji Himoro
description: Fostering the love of reading in Chavacano!
avatar: logo.jpg
#email: yourname@email.com
#github: jekyller/sustain # username
#twitter: username
#linkedin: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-119574700-1


# needed for travis-ci build
exclude: [vendor]
